Initial submission of README file containing local dev setup instruct…
chapmanu/chap-press pull request #1
Opened 2017-07-05 17:31 UTC by spence-man

Review request for README & WordPress Setup to merge with development

2017-07-05 18:29 UTC, tatwell requested changes
See comments. I updated Acceptance Criteria in Trello card.

2017-07-05 18:29 UTC, tatwell commented on README.md
> +  Download WordPress and run the server.
Let's move the WP core source into this repo. This is what we've done on Blogs:

- https://github.com/chapmanu/blogs/tree/development/public

We've tried it both ways. With our plan to deploy code using Capistrano, having the code in the repo will be simpler. Updates will be done as described there:

- https://github.com/chapmanu/blogs#to-update-the-wp-core

2017-07-05 18:29 UTC, tatwell commented on README.md
> +- PHP (5.6.30)
Requirements need to meet those specified here:

- https://wordpress.org/about/requirements/

So PHP 7. Sorry I should have clarified that in the acceptance criteria.

Red Hat (our production/staging servers) uses MariaDB, so try to set that up if possible. As far as I know, it is pretty interchangeable with MySQL (Red Hat aliases mysql to it). Still, I'd like dev/staging/production to be as similar as possible.

2017-07-05 18:31 UTC, tatwell commented on README.md
> +- PHP (5.6.30)
For reference, our Ansible Mac workstation playbook installs PHP 7:

https://github.com/chapmanu/ansible-workstation

2017-07-05 22:34 UTC, tatwell commented on README.md
> +  php -S localhost:8000
The public directory (with the WordPress core code) should be in the repository. You'll need to add it.

You'll also want to make sure no sensitive stuff is committed to the repository like config file with passwords. If you have questions about how to handle this, ping me.

 So I'd expect install instructions at this step to be something like:

```
git clone git@github.com:chapmanu/chap-press.git
cd chap-press/public
cp -v wp-config.php{-dist,}

# Update db settings in wp-config.php

php -S localhost:8000
```

2017-07-06 16:02 UTC, tatwell commented
@spence-man I succeeded in installing project locally. 👍  (I made some tweaks to instructions.)

I noticed, however, that when I go to the site in the browser, I meet the WordPress install wizard. After install, I'd like to have dev find the site fully installed and running. I'd guess this means making some tweaks to the `wp-config.php-dist` file.

On that point, let's rename `wp-config-sample.php` to `wp-config.php-dist`. That's our conventional way of marking config files.

2017-07-06 18:08 UTC, spence-man commented
@tatwell I found a solution for [installing wordpress](http://www.hongkiat.com/blog/wordpress-command-line/) using the wp cli. It creates the config file and bypasses the UI install wizard. Just have to login into wp-admin when it is finished.

Generates config file
1. `wp core config --dbname=chappress_dev --dbuser=chappress --dbpass=chappress`
2. chmod 644 wp-config.php

Wordpress Install
3. `wp core install --url=http://localhost:8000/ --title=Chappress-blog --admin_user=chappress-user --admin_password=chappress --admin_email=chappress@gmail.com`

Login
4. http://localhost:8000/wp-admin/
*without logging in, it doesn't show the admin panel (just the site)

I'm guessing we could eventually put these long terminal entries to a script or automation tool later on. I'll add this to the install instructions if it looks good.

2017-07-06 20:30 UTC, tatwell commented
Ugh. All those files make it hard to review PR. I wiped my repo and am starting from scratch with fresh clone. Hit this:

```
$ cp -v wp-config.php{-dist,}
cp: wp-config.php-dist: No such file or directory
```

2017-07-06 20:33 UTC, tatwell commented
With `wp-config.php-dist` file, why don't we just pre-fill it with the db settings from the README. Add a comment noting that they are for dev.

In future story, I'd like us to set up a simple way to switch settings based on environment like Rails does. (I think the devs rigged something like that for Blogs.)

2017-07-06 20:43 UTC, tatwell commented
Otherwise, it worked like a charm. Nice work.

What about XCode? How does that work? Is that for PHP debugging or is it a Mac thing? It doesn't look like it a requirement. Maybe list it as recommended.

2017-07-06 20:47 UTC, tatwell commented
In response to [your comment on installing WordPress](https://github.com/chapmanu/chap-press/pull/1#issuecomment-313475023), I'd recommended putting that info in its own wiki page here in this repository for now. Perhaps link to it in the README.

The info is not essential for devs working on this project, but I like that approach for future WordPress projects so it would be handy to keep for reference.

2017-07-07 21:26 UTC, tatwell commented
Excellent. Got site set up locally from scratch smooth and buttery. Only thing missing: I don't see the log. Maybe you can add a log call to the code somewhere so that it will generate the log.

Maybe put it in the config file (assuming it will work there), that way it will be easy to find and can serve as a reference for how to use logging.

2017-07-07 23:07 UTC, spence-man commented
Finally realized why the log wasn't showing after I initialized it. The gitignore file was set to ignore all logs (`*.log`). Just made the adjustment.

2017-07-07 23:14 UTC, tatwell commented
@spence-man No, you had it right before. Logs should be ignored and not included in repo.

However, when I run the local server and request a page, I'd like to see the log appear at path you noted in README. 

Also, I like the idea of putting a log call at the top or bottom of the config file to make it clear how to use the log in WordPress.

2017-07-10 16:52 UTC, tatwell commented on public/wp-config.php-dist
> +error_log($messageLog, 3, "./wp-content/debug.log");
It worked. Nice. I'd prefer a simpler interface but that can be address in the future.

2017-07-10 16:53 UTC, tatwell approved these changes
Looks good. Nice work.

2017-07-10 18:00 UTC, merged